"""Laudo ficticio para o "Gerar documento de teste" das Configuracoes (#271).

Os dados sao sinteticos e nao pertencem a nenhuma pericia: servem so para o
perito ver, no Word, a aparencia que as configuracoes vigentes produzem. O
documento passa pelo mesmo renderizador e pelas mesmas validacoes do laudo real.
"""

from __future__ import annotations

from copy import deepcopy
from dataclasses import replace

from .judicial_domain import EntityKind, NormalizedProceduralRole
from .process_participants import CaseParticipant, ParticipantOrigin, ParticipantPole, ParticipantReviewState
from .report_foundation import EditorialProfile, ExpertMasterProfile, ReportProcess, ReportSnapshot, report_snapshot_from_mapping

_SAMPLE = {'schema_version': '1.0.0',
 'report_id': 'REPORT-TEST-DOCUMENT',
 'workspace_id': '11111111-1111-4111-8111-111111111111',
 'source_snapshot': {'workspace_id': '11111111-1111-4111-8111-111111111111',
                     'case_analysis_snapshot_id': 'CASE-ANALYSIS-001',
                     'case_analysis_revision': 3,
                     'case_analysis_digest': 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
                     'inspection_session_id': 'INSPECTION-SESSION-001',
                     'inspection_session_revision': 2,
                     'inspection_session_digest': 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
                     'technical_snapshot_id': 'TECHNICAL-SNAPSHOT-001',
                     'technical_snapshot_revision': 4,
                     'technical_snapshot_digest': 'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
                     'construction_defect_analysis_snapshot_id': None,
                     'construction_defect_analysis_revision': None,
                     'construction_defect_analysis_digest': None,
                     'expert_profile_id': 'EXPERT-PROFILE-001',
                     'expert_profile_revision': 1,
                     'expert_profile_digest': 'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd'},
 'expert_profile': {'profile_id': 'EXPERT-PROFILE-001',
                    'revision': 1,
                    'full_name': 'Profissional Sintético',
                    'professional_title': 'Perito Judicial',
                    'registration': 'REG-SYNTHETIC-001',
                    'court_registration': 'COURT-SYNTHETIC-001',
                    'contact_line': 'Contato sintético não operacional'},
 'editorial_profile': {'profile_id': 'JUSTICA_PLURAL_CHAPTER_4',
                       'font_family': 'Arial',
                       'body_font_pt': 11,
                       'table_font_pt': 10,
                       'caption_font_pt': 9,
                       'alignment': 'JUSTIFIED',
                       'line_spacing': 1.15,
                       'first_line_indent_cm': 1.25,
                       'page_size': 'A4',
                       'margin_top_cm': 2,
                       'margin_bottom_cm': 2,
                       'margin_left_cm': 3,
                       'margin_right_cm': 2,
                       'hyphenation': False,
                       'overrides': []},
 'context_matrix': [{'context_id': 'CONTEXT-001',
                     'field': 'PROCESS_NUMBER',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'DOC-001',
                     'note': '0000000-00.0000.0.00.0000 (processo fictício)'},
                    {'context_id': 'CONTEXT-002',
                     'field': 'COURT',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'DOC-001',
                     'note': 'Juízo fictício — documento de teste'},
                    {'context_id': 'CONTEXT-003',
                     'field': 'PARTIES',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'PART-CLAIMANT',
                     'note': 'Participantes sintéticos canônicos.'},
                    {'context_id': 'CONTEXT-004',
                     'field': 'ADDRESSES',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'DOC-001',
                     'note': 'Endereço sintético documentado.'},
                    {'context_id': 'CONTEXT-005',
                     'field': 'CLAIM_AND_GROUNDS',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'CLAIM-001',
                     'note': 'Alegação sintética, sem promoção a fato.'},
                    {'context_id': 'CONTEXT-006',
                     'field': 'REQUESTS',
                     'required': True,
                     'status': 'PRESENT',
                     'source_id': 'QUESTION-001',
                     'note': 'Quesito sintético preservado.'}],
 'sections': [{'section_id': 'SECTION-001',
               'kind': 'IDENTIFICATION',
               'title': 'Identificação',
               'order': 1,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-002',
               'kind': 'PROCEDURAL_CONTEXT',
               'title': 'Contexto Processual',
               'order': 2,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-003',
               'kind': 'PURPOSE_OBJECT',
               'title': 'Objeto da Perícia',
               'order': 3,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-004',
               'kind': 'SCOPE',
               'title': 'Escopo',
               'order': 4,
               'required_by_cpc473': False},
              {'section_id': 'SECTION-005',
               'kind': 'DOCUMENTS_EVIDENCE',
               'title': 'Documentos e Evidências Examinados',
               'order': 5,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-006',
               'kind': 'METHODOLOGY',
               'title': 'Metodologia',
               'order': 6,
               'required_by_cpc473': False},
              {'section_id': 'SECTION-007',
               'kind': 'INSPECTION',
               'title': 'Vistoria',
               'order': 7,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-008',
               'kind': 'TECHNICAL_ANALYSIS',
               'title': 'Análise Técnica',
               'order': 8,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-009',
               'kind': 'TECHNICAL_FINDINGS',
               'title': 'Achados Técnicos',
               'order': 9,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-010',
               'kind': 'ANSWERS_TO_QUESTIONS',
               'title': 'Respostas aos Quesitos',
               'order': 10,
               'required_by_cpc473': True},
              {'section_id': 'SECTION-011',
               'kind': 'CONCLUSIONS',
               'title': 'Conclusões',
               'order': 11,
               'required_by_cpc473': False},
              {'section_id': 'SECTION-012',
               'kind': 'LIMITATIONS_RESERVATIONS',
               'title': 'Limitações e Ressalvas',
               'order': 12,
               'required_by_cpc473': False},
              {'section_id': 'SECTION-013',
               'kind': 'REFERENCES',
               'title': 'Referências',
               'order': 13,
               'required_by_cpc473': False},
              {'section_id': 'SECTION-014',
               'kind': 'ATTACHMENTS',
               'title': 'Anexos',
               'order': 14,
               'required_by_cpc473': False}],
 'claims': [{'claim_id': 'CLAIM-001',
             'section_id': 'SECTION-001',
             'text': 'Este é um documento de teste, com dados fictícios, para conferir a aparência do laudo '
                     'no Word.\n'
                     '\n'
                     '> Citação fictícia, apresentada apenas para mostrar o recuo e o corpo menor de uma '
                     'citação direta longa, como o modelo a escreve quando o parágrafo começa com o sinal de '
                     'maior seguido de espaço.',
             'authority': 'DOCUMENTED',
             'provenance': [{'provenance_id': 'PROV-001',
                             'source_kind': 'CASE_DOCUMENT',
                             'source_id': 'DOC-001',
                             'source_revision': 3}]},
            {'claim_id': 'CLAIM-002',
             'section_id': 'SECTION-002',
             'text': 'A parte sintética alegou uma ocorrência.',
             'authority': 'ALLEGED',
             'provenance': [{'provenance_id': 'PROV-002',
                             'source_kind': 'ALLEGATION',
                             'source_id': 'CLAIM-001',
                             'source_revision': 3}]},
            {'claim_id': 'CLAIM-003',
             'section_id': 'SECTION-003',
             'text': 'A decisão sintética delimitou o objeto pericial.',
             'authority': 'DECIDED_BY_COURT',
             'provenance': [{'provenance_id': 'PROV-003',
                             'source_kind': 'COURT_DECISION',
                             'source_id': 'DECISION-001',
                             'source_revision': 3}]},
            {'claim_id': 'CLAIM-004',
             'section_id': 'SECTION-005',
             'text': 'Foi examinado o documento sintético indicado.',
             'authority': 'DOCUMENTED',
             'provenance': [{'provenance_id': 'PROV-004',
                             'source_kind': 'CASE_DOCUMENT',
                             'source_id': 'DOC-001',
                             'source_revision': 3}]},
            {'claim_id': 'CLAIM-005',
             'section_id': 'SECTION-007',
             'text': 'Observou-se a condição sintética registrada.',
             'authority': 'OBSERVED',
             'provenance': [{'provenance_id': 'PROV-005',
                             'source_kind': 'FIELD_OBSERVATION',
                             'source_id': 'OBS-001',
                             'source_revision': 2}]},
            {'claim_id': 'CLAIM-006',
             'section_id': 'SECTION-008',
             'text': 'Mediu-se o valor sintético de 1250 mm.',
             'authority': 'MEASURED',
             'provenance': [{'provenance_id': 'PROV-006',
                             'source_kind': 'MEASUREMENT',
                             'source_id': 'MEASUREMENT-001',
                             'source_revision': 2}]},
            {'claim_id': 'CLAIM-007',
             'section_id': 'SECTION-009',
             'text': 'Há divergência dimensional restrita à amostra sintética.',
             'authority': 'TECHNICALLY_FOUND',
             'provenance': [{'provenance_id': 'PROV-007',
                             'source_kind': 'TECHNICAL_FINDING',
                             'source_id': 'FINDING-001',
                             'source_revision': 4}]},
            {'claim_id': 'CLAIM-008',
             'section_id': 'SECTION-010',
             'text': 'Conclui-se profissionalmente pela divergência limitada ao ponto sintético.',
             'authority': 'PROFESSIONALLY_CONCLUDED',
             'provenance': [{'provenance_id': 'PROV-008',
                             'source_kind': 'PROFESSIONAL_DECISION',
                             'source_id': 'DECISION-001',
                             'source_revision': 4}]}],
 'answers': [{'answer_id': 'ANSWER-001',
              'section_id': 'SECTION-010',
              'question_id': 'QUESTION-001',
              'text': 'A medição sintética diverge da referência documental, limitada ao ponto examinado.',
              'finding_id': 'FINDING-001',
              'evidence_ids': ['EVIDENCE-SUPPORT-001', 'EVIDENCE-CONTRARY-001'],
              'method_ids': ['METHOD-APPLICATION-001'],
              'decision_id': 'DECISION-001',
              'claim_ids': ['CLAIM-007', 'CLAIM-008']}],
 'review_decisions': [{'review_id': 'REPORT-REVIEW-001',
                       'action': 'MARK_REVIEWED',
                       'professional_id': 'EXPERT-PROFILE-001',
                       'reason': 'Revisão sintética da rastreabilidade.',
                       'timestamp': '2026-08-31T11:00:00+00:00',
                       'supersedes_review_id': None},
                      {'review_id': 'REPORT-REVIEW-002',
                       'action': 'APPROVE',
                       'professional_id': 'EXPERT-PROFILE-001',
                       'reason': 'Aprovação sintética explícita para edição controlada.',
                       'timestamp': '2026-08-31T11:01:00+00:00',
                       'supersedes_review_id': 'REPORT-REVIEW-001'}],
 'state': 'APPROVED',
 'coverage': {'sections': 14,
              'material_claims': 8,
              'traceable_claims': 8,
              'answers': 1,
              'traceable_answers': 1,
              'cpc473_required_sections': 8,
              'cpc473_present_sections': 8,
              'context_required_fields': 6,
              'context_present_fields': 6,
              'complete': True,
              'reasons': []},
 'upstream_stale': False,
 'upstream_stale_reasons': []}

_PARTIES = (
    ("AUTORA FICTÍCIA UM", ParticipantPole.ACTIVE, NormalizedProceduralRole.CLAIMANT, "Autora"),
    ("AUTOR FICTÍCIO DOIS", ParticipantPole.ACTIVE, NormalizedProceduralRole.CLAIMANT, "Autor"),
    ("AUTORA FICTÍCIA TRÊS", ParticipantPole.ACTIVE, NormalizedProceduralRole.CLAIMANT, "Autora"),
    ("AUTOR FICTÍCIO QUATRO", ParticipantPole.ACTIVE, NormalizedProceduralRole.CLAIMANT, "Autor"),
    ("EMPRESA RÉ FICTÍCIA S.A.", ParticipantPole.PASSIVE, NormalizedProceduralRole.DEFENDANT, "Ré"),
)


def sample_report(editorial_profile: EditorialProfile, expert_profile: ExpertMasterProfile | None = None) -> ReportSnapshot:
    """O laudo de teste com o perfil editorial e, se houver, o perfil profissional vigentes."""
    report = report_snapshot_from_mapping(deepcopy(_SAMPLE))
    participants = tuple(
        CaseParticipant(
            "PARTICIPANT-MAN-" + f"{index:032X}", name, pole, role, label, EntityKind.UNKNOWN, (), (),
            ParticipantOrigin.MANUAL, ParticipantReviewState.CONFIRMED, "2026-01-01T00:00:00+00:00",
        )
        for index, (name, pole, role, label) in enumerate(_PARTIES, 1)
    )
    process = ReportProcess(
        report.workspace_id, 1, "0" * 64, "0000000-00.0000.0.00.0000", "Justiça Federal", "Tribunal fictício",
        "Vara fictícia", "Cidade fictícia", "", "", "PE", "", "",
        participants=participants, participants_revision=1, participants_checksum="0" * 64,
    )
    changes = {"editorial_profile": editorial_profile, "process_record": process}
    if expert_profile is not None:
        changes["expert_profile"] = expert_profile
    return replace(report, **changes)
