"""Contratos da Application Layer local, sem infraestrutura concreta."""

from .models import (
    ArtifactRevision,
    PericiaWorkspace,
    ProcessCaseData,
    ProcessCaseSnapshot,
    WorkspaceId,
    canonical_payload_json,
    thaw_payload,
)
from .ports import (
    ArtifactRevisionNotFound,
    ArtifactRevisionRepository,
    Clock,
    IdGenerator,
    PersistenceSchemaError,
    RepositoryConflict,
    RepositoryError,
    RepositoryIntegrityError,
    WorkspaceNotFound,
    WorkspaceRepository,
)
from .services import (
    AppendArtifactRevision,
    CreateWorkspace,
    GetArtifactRevision,
    GetLatestArtifact,
    GetProcessCase,
    GetWorkspace,
    ListArtifactRevisions,
    ListWorkspaces,
    SaveProcessCase,
)

__all__ = [
    "ArtifactRevision",
    "ArtifactRevisionNotFound",
    "ArtifactRevisionRepository",
    "AppendArtifactRevision",
    "Clock",
    "CreateWorkspace",
    "GetArtifactRevision",
    "GetLatestArtifact",
    "GetWorkspace",
    "IdGenerator",
    "ListArtifactRevisions",
    "ListWorkspaces",
    "PersistenceSchemaError",
    "PericiaWorkspace",
    "ProcessCaseData",
    "ProcessCaseSnapshot",
    "RepositoryConflict",
    "RepositoryError",
    "RepositoryIntegrityError",
    "SaveProcessCase",
    "WorkspaceId",
    "WorkspaceNotFound",
    "WorkspaceRepository",
    "GetProcessCase",
    "canonical_payload_json",
    "thaw_payload",
]
