import { type FormEvent, useEffect, useState } from "react";
import { getExpertProfile, getReportSnapshot, ReportApiError, reviewReportSnapshot, saveExpertProfile, saveReportSnapshot, startReportSnapshot, type ReportEnvelope } from "../data/reportSnapshot";

type State = { kind: "loading" } | { kind: "profile-missing" } | { kind: "report-missing" } | { kind: "ready"; value: ReportEnvelope } | { kind: "error" };
export function ReportFoundationView({ workspaceId }: { workspaceId: string }) {
  const [state, setState] = useState<State>({ kind: "loading" }); const [busy, setBusy] = useState(false);
  const [profile, setProfile] = useState({ full_name: "", professional_title: "", registration: "", court_registration: "", contact_line: "" }); const [formError, setFormError] = useState(false); const [reviewReason, setReviewReason] = useState("");
  useEffect(() => { const controller = new AbortController(); getExpertProfile(workspaceId, controller.signal).then(() => getReportSnapshot(workspaceId, controller.signal).then((value) => setState({ kind: "ready", value }), (error) => { if (!controller.signal.aborted) setState({ kind: error instanceof ReportApiError && error.kind === "not-found" ? "report-missing" : "error" }); }), (error) => { if (!controller.signal.aborted) setState({ kind: error instanceof ReportApiError && error.kind === "not-found" ? "profile-missing" : "error" }); }); return () => controller.abort(); }, [workspaceId]);
  const configure = async (event: FormEvent) => { event.preventDefault(); setFormError(false); if (Object.values(profile).some((value) => !value.trim())) { setFormError(true); return; } setBusy(true); try { await saveExpertProfile(workspaceId, { profile_id: "EXPERT-PROFILE-001", revision: 1, full_name: profile.full_name.trim(), professional_title: profile.professional_title.trim(), registration: profile.registration.trim(), court_registration: profile.court_registration.trim(), contact_line: profile.contact_line.trim() }); setState({ kind: "ready", value: await startReportSnapshot(workspaceId) }); } catch { setState({ kind: "error" }); } finally { setBusy(false); } };
  if (state.kind === "loading") return <section className="status-state status-state--loading" role="status"><span className="state-rule" aria-hidden="true"/><div><h2>Carregando fundação do laudo</h2><p>Reconciliando autoridades e rastreabilidade.</p></div></section>;
  if (state.kind === "error") return <section className="status-state status-state--error" role="alert"><span className="state-mark" aria-hidden="true">!</span><div><h2>Não foi possível carregar o laudo</h2><p>Os dados locais não passaram pela validação canônica.</p></div></section>;
  if (state.kind === "profile-missing") return <section className="technical-authority"><h2>Configure o perfil mestre do perito</h2><p>Esta fonte única preenche a identificação profissional sem alterar conclusões técnicas.</p><form onSubmit={configure}><label>Nome completo<input required aria-invalid={formError} value={profile.full_name} onChange={(event) => setProfile({ ...profile, full_name: event.target.value })}/></label><label>Título profissional<input required aria-invalid={formError} value={profile.professional_title} onChange={(event) => setProfile({ ...profile, professional_title: event.target.value })}/></label><label>Registro profissional<input required aria-invalid={formError} value={profile.registration} onChange={(event) => setProfile({ ...profile, registration: event.target.value })}/></label><label>Cadastro no tribunal<input required aria-invalid={formError} value={profile.court_registration} onChange={(event) => setProfile({ ...profile, court_registration: event.target.value })}/></label><label>Contato profissional<input required aria-invalid={formError} value={profile.contact_line} onChange={(event) => setProfile({ ...profile, contact_line: event.target.value })}/></label>{formError && <p role="alert">Complete todos os campos obrigatórios do perfil mestre.</p>}<button className="primary-action" type="submit" disabled={busy}>{busy ? "Salvando…" : "Salvar perfil e iniciar laudo"}</button></form></section>;
  if (state.kind === "report-missing") return <section><h2>Laudo ainda não iniciado</h2><button className="primary-action" type="button" disabled={busy} onClick={async () => { setBusy(true); try { setState({ kind: "ready", value: await startReportSnapshot(workspaceId) }); } catch { setState({ kind: "error" }); } finally { setBusy(false); } }}>{busy ? "Iniciando…" : "Iniciar laudo"}</button></section>;
  const { snapshot } = state.value;
  return <section className="technical-workbench" aria-labelledby="report-title"><header className="technical-header"><div><p className="eyebrow">Laudo canônico · {snapshot.state}</p><h2 id="report-title">Fundação do laudo</h2><p>{snapshot.expert_profile.full_name} · {snapshot.expert_profile.registration}</p></div><div className="planning-readiness"><strong>{snapshot.coverage.complete ? "Conteúdo apto à aprovação" : "Rascunho incompleto"}</strong><span>Arial {snapshot.editorial_profile.body_font_pt} · {snapshot.editorial_profile.profile_id}</span></div></header>
    {snapshot.upstream_stale && <section className="analysis-inventory-warning" role="alert"><strong>Autoridades anteriores mudaram — revisão bloqueada</strong><ul>{snapshot.upstream_stale_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></section>}
    <section className="technical-authority"><h3>Gates de conteúdo</h3><dl><dt>Art. 319 · contexto processual</dt><dd>{snapshot.coverage.context_present_fields} de {snapshot.coverage.context_required_fields} campos presentes</dd><dt>Art. 473 · conteúdo pericial</dt><dd>{snapshot.coverage.cpc473_present_sections} de {snapshot.coverage.cpc473_required_sections} seções presentes</dd></dl>{snapshot.coverage.reasons.map((reason) => <p key={reason}>{reason}</p>)}</section>
    <ol className="technical-chain" aria-label="Seções do laudo">{snapshot.sections.map((section) => <li key={section.section_id}><h3>{section.order}. {section.title}</h3>{snapshot.claims.filter((claim) => claim.section_id === section.section_id).map((claim) => <article key={claim.claim_id}><span className="eyebrow">{claim.authority}</span><label>Texto de apresentação<textarea disabled={snapshot.review_decisions.length > 0 || busy} value={claim.text} onChange={(event) => { const next = structuredClone(snapshot); const target = next.claims.find((item) => item.claim_id === claim.claim_id); if (target) target.text = event.target.value; setState({ kind: "ready", value: { ...state.value, snapshot: next } }); }}/></label>{claim.provenance.map((item) => <small key={item.provenance_id}>{item.source_kind} · {item.source_id} · revisão {item.source_revision}</small>)}</article>)}</li>)}</ol>
    <section className="technical-authority"><h3>Revisão profissional explícita</h3><p>Editar altera apenas a apresentação; autoridade e proveniência permanecem imutáveis.</p><button type="button" disabled={busy || snapshot.review_decisions.length > 0} onClick={async () => { setBusy(true); try { setState({ kind: "ready", value: await saveReportSnapshot(workspaceId, state.value, snapshot) }); } catch { setState({ kind: "error" }); } finally { setBusy(false); } }}>Salvar rascunho</button><label>Fundamentação da revisão<textarea value={reviewReason} onChange={(event) => setReviewReason(event.target.value)}/></label>{(["MARK_REVIEWED", "APPROVE", "SUPERSEDE"] as const).map((action) => <button key={action} type="button" disabled={busy || !reviewReason.trim()} onClick={async () => { setBusy(true); try { setState({ kind: "ready", value: await reviewReportSnapshot(workspaceId, state.value, action, reviewReason) }); setReviewReason(""); } catch { setState({ kind: "error" }); } finally { setBusy(false); } }}>{action === "MARK_REVIEWED" ? "Marcar como revisado" : action === "APPROVE" ? "Aprovar laudo" : "Marcar como substituído"}</button>)}</section>
    <section className="technical-authority"><h3>Respostas rastreáveis aos quesitos</h3>{snapshot.answers.map((answer) => <article key={answer.answer_id}><strong>{answer.question_id} → {answer.finding_id}</strong><p>{answer.text}</p><small>Evidências {answer.evidence_ids.join(", ")} · métodos {answer.method_ids.join(", ")} · decisão {answer.decision_id}</small></article>)}</section>
    <details className="technical-audit"><summary>Rastreabilidade interna</summary><p>{snapshot.report_id} · revisão {state.value.revision}</p></details>
  </section>;
}
