import { type FormEvent, useEffect, useState } from "react";
import { getTechnicalSnapshot, saveTechnicalSnapshot, startTechnicalSnapshot, TechnicalSnapshotApiError, type DecisionAction, type TechnicalEnvelope } from "../data/technicalSnapshot";

type State = { kind: "loading" } | { kind: "empty" } | { kind: "ready"; value: TechnicalEnvelope } | { kind: "error" };
export function TechnicalFindingsView({ workspaceId }: { workspaceId: string }) {
  const [state, setState] = useState<State>({ kind: "loading" }); const [starting, setStarting] = useState(false);
  const [decisionAction, setDecisionAction] = useState<DecisionAction>("REJECT"); const [professional, setProfessional] = useState("");
  const [sourceKind, setSourceKind] = useState("MEASUREMENT");
  const emptyFields = { source: "", proposition: "", relevance: "", evidenceLimitation: "", method: "", procedure: "", output: "", methodLimitation: "", proposal: "", scope: "", findingLimitation: "", uncertainty: "", uncertaintyImpact: "", contraryEvidence: "", question: "", modifiedProposition: "", reason: "" };
  const [fields, setFields] = useState(emptyFields);
  const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(false);
  const [reviewProposal, setReviewProposal] = useState(""); const [reviewAction, setReviewAction] = useState<DecisionAction>("REJECT");
  const [reviewProfessional, setReviewProfessional] = useState(""); const [reviewReason, setReviewReason] = useState(""); const [reviewModified, setReviewModified] = useState(""); const [resolveConflicts, setResolveConflicts] = useState(false);
  useEffect(() => { const controller = new AbortController(); getTechnicalSnapshot(workspaceId, controller.signal).then((value) => setState({ kind: "ready", value }), (error) => { if (!controller.signal.aborted) setState({ kind: error instanceof TechnicalSnapshotApiError && error.kind === "not-found" ? "empty" : "error" }); }); return () => controller.abort(); }, [workspaceId]);
  if (state.kind === "loading") return <section className="status-state status-state--loading" role="status"><span className="state-rule" aria-hidden="true"/><div><h2>Carregando cadeia técnica</h2><p>Reconciliando fontes, evidências e decisões profissionais.</p></div></section>;
  if (state.kind === "error") return <section className="status-state status-state--error" role="alert"><span className="state-mark" aria-hidden="true">!</span><div><h2>Não foi possível carregar a cadeia técnica</h2><p>Verifique os registros locais e tente novamente.</p></div></section>;
  if (state.kind === "empty") return <section className="technical-empty"><h2>Cadeia técnica ainda não iniciada</h2><p>O início vincula as revisões atuais da análise do caso e da vistoria sem promover nenhuma fonte automaticamente.</p><button className="primary-action" type="button" disabled={starting} onClick={async () => { setStarting(true); try { setState({ kind: "ready", value: await startTechnicalSnapshot(workspaceId) }); } catch { setState({ kind: "error" }); } finally { setStarting(false); } }}>{starting ? "Iniciando…" : "Iniciar cadeia técnica"}</button></section>;
  const snapshot = state.value.snapshot;
  const setField = (name: keyof typeof fields, value: string) => setFields((current) => ({ ...current, [name]: value }));
  const saveChain = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true); setSaveError(false);
    const optional = new Set(["contraryEvidence", "question", "modifiedProposition"]);
    const required = [...Object.entries(fields).filter(([name]) => !optional.has(name)).map(([, value]) => value), professional];
    const contraryId = fields.contraryEvidence.trim(); const questionId = fields.question.trim();
    if (required.some((value) => !value.trim()) || (decisionAction === "MODIFY" && !fields.modifiedProposition.trim()) || (contraryId && !snapshot.evidence_items.some((item) => item.evidence_id === contraryId)) || snapshot.upstream_stale) { setSaveError(true); setSaving(false); return; }
    const next = structuredClone(snapshot); const token = crypto.randomUUID().replaceAll("-", "").toUpperCase(); const now = new Date().toISOString();
    const evidenceId = `EVIDENCE-${token}`, assessmentId = `ASSESSMENT-${token}`, sourceLinkId = `SOURCE-LINK-${token}`;
    const methodId = `METHOD-${token}`, inputId = `METHOD-INPUT-${token}`, outputId = `METHOD-OUTPUT-${token}`;
    const proposalId = `PROPOSAL-${token}`, decisionId = `DECISION-${token}`, uncertaintyId = `UNCERTAINTY-${token}`;
    const evidenceLimitId = `LIMIT-EVIDENCE-${token}`, methodLimitId = `LIMIT-METHOD-${token}`, proposalLimitId = `LIMIT-PROPOSAL-${token}`;
    next.evidence_items.push({ evidence_id: evidenceId, proposition: fields.proposition.trim(), assessment_id: assessmentId });
    const caseSource = sourceKind.startsWith("CASE_") || sourceKind === "DOCUMENTED_ALLEGATION";
    next.source_links.push({ link_id: sourceLinkId, evidence_id: evidenceId, source_kind: sourceKind, source_id: fields.source.trim(), source_revision: caseSource ? next.source_snapshot.case_analysis_revision : next.source_snapshot.inspection_session_revision, provenance: `Fonte indicada explicitamente no snapshot ${next.snapshot_id}.` });
    next.evidence_assessments.push({ assessment_id: assessmentId, evidence_id: evidenceId, why_relevant: fields.relevance.trim(), supported_proposition: fields.proposition.trim(), limitation_ids: [evidenceLimitId], contrary_evidence_ids: contraryId ? [contraryId] : [], source_link_ids: [sourceLinkId], review_state: "APPROVED", reviewer: professional.trim(), reviewed_at: now });
    next.limitations.push({ limitation_id: evidenceLimitId, owner_kind: "EVIDENCE", owner_id: evidenceId, kind: "SOURCE_LIMITATION", description: fields.evidenceLimitation.trim() });
    next.method_inputs.push({ input_id: inputId, method_application_id: methodId, evidence_id: evidenceId, role: "PRIMARY_INPUT" });
    next.method_outputs.push({ output_id: outputId, method_application_id: methodId, description: fields.output.trim(), provenance: `Saída do método ${methodId}; não é decisão profissional.` });
    next.method_applications.push({ method_application_id: methodId, method_identity: fields.method.trim(), selection_authority: professional.trim(), procedure: fields.procedure.trim(), parameters: [], input_ids: [inputId], output_ids: [outputId], limitation_ids: [methodLimitId], normative_references: [], execution_revision: state.value.revision });
    next.limitations.push({ limitation_id: methodLimitId, owner_kind: "METHOD", owner_id: methodId, kind: "METHOD_LIMITATION", description: fields.methodLimitation.trim() });
    next.uncertainties.push({ uncertainty_id: uncertaintyId, proposal_id: proposalId, kind: "EXPLICIT_UNCERTAINTY", description: fields.uncertainty.trim(), impact: fields.uncertaintyImpact.trim() });
    next.limitations.push({ limitation_id: proposalLimitId, owner_kind: "PROPOSAL", owner_id: proposalId, kind: "SCOPE_LIMITATION", description: fields.findingLimitation.trim() });
    next.finding_proposals.push({ proposal_id: proposalId, technical_proposition: fields.proposal.trim(), origin: "PROFESSIONAL_PROPOSAL", method_application_ids: [methodId], supporting_evidence_ids: [evidenceId], contrary_evidence_ids: contraryId ? [contraryId] : [], limitation_ids: [proposalLimitId], uncertainty_ids: [uncertaintyId], scope: fields.scope.trim() });
    if (contraryId) next.conflicts.push({ conflict_id: `CONFLICT-${token}`, proposal_id: proposalId, contrary_evidence_ids: [contraryId], status: "UNRESOLVED", resolution_reasoning: null, decision_id: null });
    const modified = decisionAction === "MODIFY" ? fields.modifiedProposition.trim() : null;
    next.decisions.push({ decision_id: decisionId, proposal_id: proposalId, action: decisionAction, professional_id: professional.trim(), reason: fields.reason.trim(), modified_proposition: modified, timestamp: now, supersedes_decision_id: null });
    if (decisionAction !== "REJECT") { const findingId = `FINDING-${token}`; next.findings.push({ finding_id: findingId, proposal_id: proposalId, decision_id: decisionId, technical_proposition: modified ?? fields.proposal.trim(), scope: fields.scope.trim() }); if (questionId) next.question_links.push({ link_id: `QUESTION-LINK-${token}`, question_id: questionId, finding_id: findingId, relevance: "SubsÃ­dio tÃ©cnico futuro; nÃ£o constitui resposta final." }); }
    next.coverage = { evidence_items: next.evidence_items.length, approved_evidence: next.evidence_items.length, method_applications: next.method_applications.length, finding_proposals: next.finding_proposals.length, effective_findings: next.findings.length, unresolved_conflicts: next.conflicts.filter((item) => item.status === "UNRESOLVED").length, complete: next.finding_proposals.length > 0 && next.findings.length === next.finding_proposals.length, reasons: decisionAction === "REJECT" ? ["Uma proposta foi rejeitada explicitamente e permanece não efetiva."] : [] };
    try { setState({ kind: "ready", value: await saveTechnicalSnapshot(workspaceId, state.value.revision, next) }); setFields(emptyFields); setProfessional(""); setDecisionAction("REJECT"); setSourceKind("MEASUREMENT"); } catch { setSaveError(true); } finally { setSaving(false); }
  };
  const saveReview = async (event: FormEvent) => {
    event.preventDefault(); setSaveError(false);
    const proposal = snapshot.finding_proposals.find((item) => item.proposal_id === reviewProposal);
    const previous = snapshot.decisions.filter((item) => item.proposal_id === reviewProposal).sort((a, b) => Date.parse(a.timestamp) - Date.parse(b.timestamp)).at(-1);
    const existingFinding = snapshot.findings.find((item) => item.proposal_id === reviewProposal);
    const hasDependents = existingFinding && snapshot.dependencies.some((item) => item.finding_id === existingFinding.finding_id || item.depends_on_finding_id === existingFinding.finding_id);
    if (!proposal || !previous || !reviewProfessional.trim() || !reviewReason.trim() || (reviewAction === "MODIFY" && !reviewModified.trim()) || (reviewAction === "REJECT" && hasDependents)) { setSaveError(true); return; }
    setSaving(true); const next = structuredClone(snapshot); const token = crypto.randomUUID().replaceAll("-", "").toUpperCase();
    const decisionId = `DECISION-${token}`; let timestamp = new Date().toISOString();
    if (Date.parse(timestamp) <= Date.parse(previous.timestamp)) timestamp = new Date(Date.parse(previous.timestamp) + 1).toISOString();
    next.decisions.push({ decision_id: decisionId, proposal_id: proposal.proposal_id, action: reviewAction, professional_id: reviewProfessional.trim(), reason: reviewReason.trim(), modified_proposition: reviewAction === "MODIFY" ? reviewModified.trim() : null, timestamp, supersedes_decision_id: previous.decision_id });
    if (existingFinding) {
      if (reviewAction === "REJECT") { next.findings = next.findings.filter((item) => item.finding_id !== existingFinding.finding_id); next.question_links = next.question_links.filter((item) => item.finding_id !== existingFinding.finding_id); }
      else { const current = next.findings.find((item) => item.finding_id === existingFinding.finding_id)!; current.decision_id = decisionId; current.technical_proposition = reviewAction === "MODIFY" ? reviewModified.trim() : proposal.technical_proposition; }
    } else if (reviewAction !== "REJECT") next.findings.push({ finding_id: `FINDING-${token}`, proposal_id: proposal.proposal_id, decision_id: decisionId, technical_proposition: reviewAction === "MODIFY" ? reviewModified.trim() : proposal.technical_proposition, scope: proposal.scope });
    if (resolveConflicts) for (const conflict of next.conflicts.filter((item) => item.proposal_id === proposal.proposal_id)) { conflict.status = "RESOLVED"; conflict.resolution_reasoning = reviewReason.trim(); conflict.decision_id = decisionId; }
    next.coverage = { ...next.coverage, effective_findings: next.findings.length, unresolved_conflicts: next.conflicts.filter((item) => item.status === "UNRESOLVED").length, complete: next.finding_proposals.length > 0 && next.findings.length === next.finding_proposals.length };
    try { setState({ kind: "ready", value: await saveTechnicalSnapshot(workspaceId, state.value.revision, next) }); setReviewProposal(""); setReviewProfessional(""); setReviewReason(""); setReviewModified(""); setResolveConflicts(false); setReviewAction("REJECT"); } catch { setSaveError(true); } finally { setSaving(false); }
  };
  return <section className="technical-workbench" aria-labelledby="technical-chain-title">
    <header className="planning-overview"><div><h2 id="technical-chain-title">Cadeia técnica</h2><p>Fonte ou observação → evidência avaliada → método aplicado → proposta → decisão profissional.</p></div><div className="planning-readiness"><strong>{snapshot.coverage.complete ? "Cadeia efetiva" : "Cadeia em construção"}</strong><span>{snapshot.coverage.effective_findings} de {snapshot.coverage.finding_proposals} propostas efetivas</span></div></header>
    {snapshot.upstream_stale && <section className="analysis-inventory-warning" role="alert"><strong>Fontes anteriores mudaram — não continue</strong><ul>{snapshot.upstream_stale_reasons.map((reason) => <li key={reason}>{reason}</li>)}</ul></section>}
    <ol className="technical-chain" aria-label="Etapas da cadeia técnica">
      <li><h3>1. Evidência avaliada</h3>{snapshot.evidence_items.length ? snapshot.evidence_items.map((item) => { const assessment = snapshot.evidence_assessments.find((candidate) => candidate.assessment_id === item.assessment_id); return <article key={item.evidence_id}><strong>{item.proposition}</strong><p>{assessment?.why_relevant}</p><small>{assessment?.review_state} · {assessment?.reviewer}</small></article>; }) : <p>Nenhuma fonte foi promovida a evidência.</p>}</li>
      <li><h3>2. Método aplicado</h3>{snapshot.method_applications.length ? snapshot.method_applications.map((item) => <article key={item.method_application_id}><strong>{item.method_identity}</strong><p>{item.procedure}</p><small>Revisão de execução {item.execution_revision} · seleção {item.selection_authority}</small></article>) : <p>Nenhum método aplicado.</p>}</li>
      <li><h3>3. Proposta técnica</h3><p className="boundary-note">Uma proposta não produz conclusão efetiva por si só.</p>{snapshot.finding_proposals.map((item) => <article key={item.proposal_id}><strong>{item.technical_proposition}</strong><p>{item.scope}</p><small>{item.origin}</small></article>)}</li>
      <li><h3>4. Decisão profissional</h3><p className="boundary-note">Somente decisão profissional explícita torna um achado efetivo.</p>{snapshot.decisions.map((item) => <article key={item.decision_id}><strong>{item.action}</strong><p>{item.reason}</p><small>{item.professional_id} · {item.timestamp}</small></article>)}</li>
    </ol>
    <section className="technical-authority"><h3>Registrar cadeia e autoridade profissional</h3><p>Todos os elos são explícitos. O padrão inicial é rejeitar; aprovação nunca é presumida.</p><form onSubmit={saveChain}>
      <fieldset><legend>Fonte → evidência</legend>
        <label>Tipo canônico da fonte<select value={sourceKind} onChange={(event) => setSourceKind(event.target.value)}><option value="MEASUREMENT">Medição</option><option value="FIELD_OBSERVATION">Observação de campo</option><option value="PHOTO_RECORD">Fotografia</option><option value="DOCUMENTED_ALLEGATION">Alegação documentada</option><option value="CASE_DOCUMENT">Documento do caso</option></select></label>
        <label>Identidade da fonte ou observação<input value={fields.source} onChange={(event) => setField("source", event.target.value)}/></label><label>Proposição sustentada<textarea value={fields.proposition} onChange={(event) => setField("proposition", event.target.value)}/></label><label>Por que é relevante<textarea value={fields.relevance} onChange={(event) => setField("relevance", event.target.value)}/></label><label>Limitação da evidência<textarea value={fields.evidenceLimitation} onChange={(event) => setField("evidenceLimitation", event.target.value)}/></label>
        <label>Evidência contrária existente (opcional)<input value={fields.contraryEvidence} onChange={(event) => setField("contraryEvidence", event.target.value)}/></label>
      </fieldset>
      <fieldset><legend>Evidência → método</legend><label>Método selecionado<input value={fields.method} onChange={(event) => setField("method", event.target.value)}/></label><label>Procedimento aplicado<textarea value={fields.procedure} onChange={(event) => setField("procedure", event.target.value)}/></label><label>Saída do método<textarea value={fields.output} onChange={(event) => setField("output", event.target.value)}/></label><label>Limitação do método<textarea value={fields.methodLimitation} onChange={(event) => setField("methodLimitation", event.target.value)}/></label></fieldset>
      <fieldset><legend>Método → proposta</legend><label>Proposição técnica proposta<textarea value={fields.proposal} onChange={(event) => setField("proposal", event.target.value)}/></label><label>Escopo técnico<textarea value={fields.scope} onChange={(event) => setField("scope", event.target.value)}/></label><label>Limitação do achado<textarea value={fields.findingLimitation} onChange={(event) => setField("findingLimitation", event.target.value)}/></label><label>Incerteza<textarea value={fields.uncertainty} onChange={(event) => setField("uncertainty", event.target.value)}/></label><label>Impacto da incerteza<textarea value={fields.uncertaintyImpact} onChange={(event) => setField("uncertaintyImpact", event.target.value)}/></label><label>Quesito relacionado (opcional)<input value={fields.question} onChange={(event) => setField("question", event.target.value)}/></label></fieldset>
      <fieldset><legend>Decisão profissional explícita</legend><label>Ação profissional<select value={decisionAction} onChange={(event) => setDecisionAction(event.target.value as DecisionAction)}><option value="REJECT">Rejeitar proposta</option><option value="APPROVE">Aprovar proposta</option><option value="MODIFY">Modificar e aprovar</option></select></label>{decisionAction === "MODIFY" && <label>Proposição modificada<textarea value={fields.modifiedProposition} onChange={(event) => setField("modifiedProposition", event.target.value)}/></label>}<label>Profissional responsável<input value={professional} onChange={(event) => setProfessional(event.target.value)}/></label><label>Razão da decisão<textarea value={fields.reason} onChange={(event) => setField("reason", event.target.value)}/></label></fieldset>
      {saveError && <p role="alert">A cadeia não foi salva. Complete todos os elos e confirme que os upstreams permanecem atuais.</p>}<button className="primary-action" type="submit" disabled={saving || snapshot.upstream_stale}>{saving ? "Salvando…" : "Salvar cadeia e decisão"}</button>
    </form></section>
    <section className="technical-authority"><h3>Revisar decisão existente</h3><p>Uma nova decisão sempre referencia e supera linearmente a decisão anterior da mesma proposta.</p><form onSubmit={saveReview}>
      <label>Proposta em revisão<select value={reviewProposal} onChange={(event) => setReviewProposal(event.target.value)}><option value="">Selecione</option>{snapshot.finding_proposals.map((item) => <option key={item.proposal_id} value={item.proposal_id}>{item.proposal_id}</option>)}</select></label>
      <label>Nova ação profissional<select value={reviewAction} onChange={(event) => setReviewAction(event.target.value as DecisionAction)}><option value="REJECT">Rejeitar</option><option value="APPROVE">Aprovar</option><option value="MODIFY">Modificar e aprovar</option></select></label>
      {reviewAction === "MODIFY" && <label>Nova proposição técnica<textarea value={reviewModified} onChange={(event) => setReviewModified(event.target.value)}/></label>}
      <label>Profissional revisor<input value={reviewProfessional} onChange={(event) => setReviewProfessional(event.target.value)}/></label><label>Fundamentação da revisão<textarea value={reviewReason} onChange={(event) => setReviewReason(event.target.value)}/></label>
      <label><input type="checkbox" checked={resolveConflicts} onChange={(event) => setResolveConflicts(event.target.checked)}/> Resolver conflitos explícitos desta proposta com esta decisão</label>
      <button className="primary-action" type="submit" disabled={saving || snapshot.upstream_stale}>Salvar revisão profissional</button>
    </form></section>
    <details className="technical-audit"><summary>Auditoria da cadeia</summary><dl><dt>Case Analysis</dt><dd>{snapshot.source_snapshot.case_analysis_snapshot_id} · revisão {snapshot.source_snapshot.case_analysis_revision}</dd><dt>Vistoria</dt><dd>{snapshot.source_snapshot.inspection_session_id} · revisão {snapshot.source_snapshot.inspection_session_revision}</dd><dt>Snapshot</dt><dd>{snapshot.snapshot_id} · revisão {state.value.revision}</dd></dl></details>
  </section>;
}
