import { type FormEvent, useEffect, useState } from "react";
import { addTechnicalEvidenceProposal, getTechnicalSnapshot, proposeTechnicalFinding, reviewTechnicalEvidence, reviewTechnicalFinding, selectTechnicalMethod, startTechnicalSnapshot, TechnicalSnapshotApiError, type DecisionAction, type TechnicalEnvelope } from "../data/technicalSnapshot";

type State = { kind: "loading" } | { kind: "empty" } | { kind: "ready"; value: TechnicalEnvelope } | { kind: "error" };
const filled = (...values: string[]) => values.every((value) => value.trim());

export function TechnicalFindingsView({ workspaceId }: { workspaceId: string }) {
  const [state, setState] = useState<State>({ kind: "loading" }); const [busy, setBusy] = useState(false); const [saveError, setSaveError] = useState(false);
  const [sourceKind, setSourceKind] = useState("MEASUREMENT"); const [sourceId, setSourceId] = useState(""); const [proposition, setProposition] = useState(""); const [relevance, setRelevance] = useState("");
  const [evidenceId, setEvidenceId] = useState(""); const [evidenceAction, setEvidenceAction] = useState<"APPROVE" | "REJECT">("REJECT"); const [professional, setProfessional] = useState(""); const [reason, setReason] = useState("");
  const [methodEvidenceId, setMethodEvidenceId] = useState(""); const [method, setMethod] = useState(""); const [procedure, setProcedure] = useState(""); const [output, setOutput] = useState(""); const [methodProfessional, setMethodProfessional] = useState("");
  const [methodId, setMethodId] = useState(""); const [proposal, setProposal] = useState(""); const [scope, setScope] = useState(""); const [limitation, setLimitation] = useState(""); const [uncertainty, setUncertainty] = useState(""); const [uncertaintyImpact, setUncertaintyImpact] = useState("");
  const [reviewProposal, setReviewProposal] = useState(""); const [reviewAction, setReviewAction] = useState<DecisionAction>("REJECT"); const [reviewProfessional, setReviewProfessional] = useState(""); const [reviewReason, setReviewReason] = useState(""); const [reviewModified, setReviewModified] = useState(""); const [resolveConflicts, setResolveConflicts] = useState(false);
  useEffect(() => { const controller = new AbortController(); getTechnicalSnapshot(workspaceId, controller.signal).then((value) => setState({ kind: "ready", value }), (error) => { if (!controller.signal.aborted) setState({ kind: error instanceof TechnicalSnapshotApiError && error.kind === "not-found" ? "empty" : "error" }); }); return () => controller.abort(); }, [workspaceId]);
  const run = async (operation: () => Promise<TechnicalEnvelope>) => { setBusy(true); setSaveError(false); try { setState({ kind: "ready", value: await operation() }); } catch { setSaveError(true); } finally { setBusy(false); } };
  if (state.kind === "loading") return <section className="status-state status-state--loading" role="status"><span className="state-rule" aria-hidden="true"/><div><h2>Carregando cadeia técnica</h2><p>Reconciliando fontes, evidências e decisões profissionais.</p></div></section>;
  if (state.kind === "error") return <section className="status-state status-state--error" role="alert"><span className="state-mark" aria-hidden="true">!</span><div><h2>Não foi possível carregar a cadeia técnica</h2><p>Verifique os registros locais e tente novamente.</p></div></section>;
  if (state.kind === "empty") return <section className="technical-empty"><h2>Cadeia técnica ainda não iniciada</h2><p>O início vincula as autoridades atuais sem promover nenhuma fonte automaticamente.</p><button className="primary-action" type="button" disabled={busy} onClick={() => run(() => startTechnicalSnapshot(workspaceId))}>{busy ? "Iniciando…" : "Iniciar cadeia técnica"}</button></section>;
  const { snapshot, revision } = state.value; const blocked = busy || snapshot.upstream_stale;
  const submit = (event: FormEvent, valid: boolean, operation: () => Promise<TechnicalEnvelope>) => { event.preventDefault(); if (!valid) { setSaveError(true); return; } void run(operation); };
  const pendingEvidence = snapshot.evidence_items.filter((item) => snapshot.evidence_assessments.find((assessment) => assessment.assessment_id === item.assessment_id)?.review_state === "PENDING");
  const approvedEvidence = snapshot.evidence_items.filter((item) => snapshot.evidence_assessments.find((assessment) => assessment.assessment_id === item.assessment_id)?.review_state === "APPROVED");
  return <section className="technical-workbench" aria-labelledby="technical-chain-title">
    <header className="planning-overview"><div><h2 id="technical-chain-title">Cadeia técnica</h2><p>Proposta de evidência → revisão humana → método selecionado → proposta técnica → decisão profissional.</p></div><div className="planning-readiness"><strong>{snapshot.coverage.complete ? "Cadeia efetiva" : "Cadeia em construção"}</strong><span>{snapshot.coverage.effective_findings} de {snapshot.coverage.finding_proposals} propostas efetivas</span></div></header>
    {snapshot.upstream_stale && <section className="analysis-inventory-warning" role="alert"><strong>Fontes anteriores mudaram — não continue</strong><ul>{snapshot.upstream_stale_reasons.map((item) => <li key={item}>{item}</li>)}</ul></section>}
    <ol className="technical-chain" aria-label="Etapas da cadeia técnica">
      <li><h3>1. Evidências</h3>{snapshot.evidence_items.map((item) => { const assessment = snapshot.evidence_assessments.find((candidate) => candidate.assessment_id === item.assessment_id); return <article key={item.evidence_id}><strong>{item.proposition}</strong><p>{assessment?.why_relevant}</p><small>{assessment?.review_state} · {assessment?.reviewer ?? "sem revisão profissional"}</small></article>; })}</li>
      <li><h3>2. Métodos selecionados</h3>{snapshot.method_applications.map((item) => <article key={item.method_application_id}><strong>{item.method_identity}</strong><p>{item.procedure}</p><small>{item.selection_authority}</small></article>)}</li>
      <li><h3>3. Propostas técnicas</h3><p className="boundary-note">Uma proposta não produz conclusão efetiva por si só.</p>{snapshot.finding_proposals.map((item) => <article key={item.proposal_id}><strong>{item.technical_proposition}</strong><p>{item.scope}</p><small>{item.origin}</small></article>)}</li>
      <li><h3>4. Decisões profissionais</h3><p className="boundary-note">Somente decisão profissional explícita torna um achado efetivo.</p>{snapshot.decisions.map((item) => <article key={item.decision_id}><strong>{item.action}</strong><p>{item.reason}</p><small>{item.professional_id} · {item.timestamp}</small></article>)}</li>
    </ol>
    <section className="technical-authority"><h3>1. Propor evidência</h3><p>Esta etapa registra material candidato; não o aprova.</p><form onSubmit={(event) => submit(event, filled(sourceId, proposition, relevance), () => addTechnicalEvidenceProposal(workspaceId, { source_kind: sourceKind, source_id: sourceId.trim(), proposition: proposition.trim(), why_relevant: relevance.trim(), expected_revision: revision }))}>
      <label>Tipo canônico da fonte<select value={sourceKind} onChange={(event) => setSourceKind(event.target.value)}><option value="MEASUREMENT">Medição</option><option value="FIELD_OBSERVATION">Observação de campo</option><option value="PHOTO_RECORD">Fotografia</option><option value="DOCUMENTED_ALLEGATION">Alegação documentada</option><option value="CASE_DOCUMENT">Documento do caso</option></select></label><label>Identidade da fonte ou observação<input value={sourceId} onChange={(event) => setSourceId(event.target.value)}/></label><label>Proposição sustentada<textarea value={proposition} onChange={(event) => setProposition(event.target.value)}/></label><label>Por que é relevante<textarea value={relevance} onChange={(event) => setRelevance(event.target.value)}/></label><button className="primary-action" disabled={blocked}>Registrar proposta de evidência</button>
    </form></section>
    <section className="technical-authority"><h3>2. Revisar evidência</h3><p>O servidor registra a identidade e o instante canônico da revisão.</p><form onSubmit={(event) => submit(event, filled(evidenceId, professional, reason), () => reviewTechnicalEvidence(workspaceId, { evidence_id: evidenceId, action: evidenceAction, professional_id: professional.trim(), reason: reason.trim(), expected_revision: revision }))}>
      <label>Evidência pendente<select value={evidenceId} onChange={(event) => setEvidenceId(event.target.value)}><option value="">Selecione</option>{pendingEvidence.map((item) => <option key={item.evidence_id} value={item.evidence_id}>{item.evidence_id}</option>)}</select></label><label>Ação profissional<select value={evidenceAction} onChange={(event) => setEvidenceAction(event.target.value as "APPROVE" | "REJECT")}><option value="REJECT">Rejeitar</option><option value="APPROVE">Aprovar</option></select></label><label>Profissional responsável<input value={professional} onChange={(event) => setProfessional(event.target.value)}/></label><label>Razão da revisão<textarea value={reason} onChange={(event) => setReason(event.target.value)}/></label><button className="primary-action" disabled={blocked}>Salvar revisão da evidência</button>
    </form></section>
    <section className="technical-authority"><h3>3. Selecionar método</h3><form onSubmit={(event) => submit(event, filled(methodEvidenceId, method, procedure, output, methodProfessional), () => selectTechnicalMethod(workspaceId, { evidence_id: methodEvidenceId, method_identity: method.trim(), procedure: procedure.trim(), output: output.trim(), professional_id: methodProfessional.trim(), expected_revision: revision }))}>
      <label>Evidência aprovada<select value={methodEvidenceId} onChange={(event) => setMethodEvidenceId(event.target.value)}><option value="">Selecione</option>{approvedEvidence.map((item) => <option key={item.evidence_id} value={item.evidence_id}>{item.evidence_id}</option>)}</select></label><label>Método selecionado<input value={method} onChange={(event) => setMethod(event.target.value)}/></label><label>Procedimento aplicado<textarea value={procedure} onChange={(event) => setProcedure(event.target.value)}/></label><label>Saída do método<textarea value={output} onChange={(event) => setOutput(event.target.value)}/></label><label>Profissional que selecionou o método<input value={methodProfessional} onChange={(event) => setMethodProfessional(event.target.value)}/></label><button className="primary-action" disabled={blocked}>Salvar seleção do método</button>
    </form></section>
    <section className="technical-authority"><h3>4. Propor achado técnico</h3><p>Subsídio técnico futuro; não constitui resposta final.</p><form onSubmit={(event) => submit(event, filled(methodId, proposal, scope, limitation, uncertainty, uncertaintyImpact), () => proposeTechnicalFinding(workspaceId, { method_application_id: methodId, technical_proposition: proposal.trim(), scope: scope.trim(), limitation: limitation.trim(), uncertainty: uncertainty.trim(), uncertainty_impact: uncertaintyImpact.trim(), origin: "PROFESSIONAL_PROPOSAL", contrary_evidence_ids: [], expected_revision: revision }))}>
      <label>Método de suporte<select value={methodId} onChange={(event) => setMethodId(event.target.value)}><option value="">Selecione</option>{snapshot.method_applications.map((item) => <option key={item.method_application_id} value={item.method_application_id}>{item.method_application_id}</option>)}</select></label><label>Proposição técnica proposta<textarea value={proposal} onChange={(event) => setProposal(event.target.value)}/></label><label>Escopo técnico<textarea value={scope} onChange={(event) => setScope(event.target.value)}/></label><label>Limitação do achado<textarea value={limitation} onChange={(event) => setLimitation(event.target.value)}/></label><label>Incerteza<textarea value={uncertainty} onChange={(event) => setUncertainty(event.target.value)}/></label><label>Impacto da incerteza<textarea value={uncertaintyImpact} onChange={(event) => setUncertaintyImpact(event.target.value)}/></label><button className="primary-action" disabled={blocked}>Registrar proposta técnica</button>
    </form></section>
    <section className="technical-authority"><h3>5. Decidir sobre proposta</h3><p>A decisão e o achado efetivo são criados pelo servidor; o histórico anterior permanece intacto.</p><form onSubmit={(event) => submit(event, filled(reviewProposal, reviewProfessional, reviewReason) && (reviewAction !== "MODIFY" || !!reviewModified.trim()), () => reviewTechnicalFinding(workspaceId, { proposal_id: reviewProposal, action: reviewAction, professional_id: reviewProfessional.trim(), reason: reviewReason.trim(), modified_proposition: reviewAction === "MODIFY" ? reviewModified.trim() : null, resolve_conflicts: resolveConflicts, expected_revision: revision }))}>
      <label>Proposta em revisão<select value={reviewProposal} onChange={(event) => setReviewProposal(event.target.value)}><option value="">Selecione</option>{snapshot.finding_proposals.map((item) => <option key={item.proposal_id} value={item.proposal_id}>{item.proposal_id}</option>)}</select></label><label>Nova ação profissional<select value={reviewAction} onChange={(event) => setReviewAction(event.target.value as DecisionAction)}><option value="REJECT">Rejeitar</option><option value="APPROVE">Aprovar</option><option value="MODIFY">Modificar e aprovar</option></select></label>{reviewAction === "MODIFY" && <label>Nova proposição técnica<textarea value={reviewModified} onChange={(event) => setReviewModified(event.target.value)}/></label>}<label>Profissional revisor<input value={reviewProfessional} onChange={(event) => setReviewProfessional(event.target.value)}/></label><label>Fundamentação da revisão<textarea value={reviewReason} onChange={(event) => setReviewReason(event.target.value)}/></label><label><input type="checkbox" checked={resolveConflicts} onChange={(event) => setResolveConflicts(event.target.checked)}/> Resolver conflitos explícitos desta proposta</label><button className="primary-action" disabled={blocked}>Salvar decisão profissional</button>
    </form></section>
    {saveError && <p role="alert">A operação foi recusada. Revise os campos e confirme que as fontes permanecem atuais.</p>}
    <details className="technical-audit"><summary>Auditoria da cadeia</summary><dl><dt>Case Analysis</dt><dd>{snapshot.source_snapshot.case_analysis_snapshot_id} · revisão {snapshot.source_snapshot.case_analysis_revision}</dd><dt>Vistoria</dt><dd>{snapshot.source_snapshot.inspection_session_id} · revisão {snapshot.source_snapshot.inspection_session_revision}</dd><dt>Snapshot</dt><dd>{snapshot.snapshot_id} · revisão {revision}</dd></dl></details>
  </section>;
}
