"""Registry first-party de capabilities periciais; ausência falha fechada."""

_REGISTRY={
 "VICIOS_CONSTRUTIVOS":(True,"VICIOS_CONSTRUTIVOS","VICIOS_CONSTRUTIVOS",True,"IMPLEMENTADO"),
 "AVALIACAO_IMOBILIARIA":(True,"AVALIACAO_IMOBILIARIA","AVALIACAO_IMOBILIARIA",False,"PERFIL_IMPLEMENTADO_MOTOR_NAO_IMPLEMENTADO"),
 "ENGENHARIA_RODOVIARIA":(True,"ENGENHARIA_RODOVIARIA","ENGENHARIA_RODOVIARIA",False,"PERFIL_IMPLEMENTADO_MOTOR_NAO_IMPLEMENTADO"),
 "SINISTRO_VIARIO":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "ORCAMENTO_E_MEDICAO":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "ESTRUTURAS":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "TOPOGRAFIA_E_DIVISAS":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "INSTALACOES_PREDIAIS":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "SEGURANCA_VIARIA":(True,None,None,False,"PERFIL_ESPECIALIZADO_NAO_IMPLEMENTADO"),
 "OUTRO":(True,"OUTRO","OUTRO",False,"FALLBACK_GENERICO_EXPLICITO"),
}
def capability(tipo):
    classificada,delimitacao,planejamento,motor,status=_REGISTRY.get(tipo,(False,None,None,False,"TIPO_NAO_REGISTRADO"))
    return {"TIPO":tipo,"CLASSIFICACAO_SUPORTADA":classificada,"PERFIL_DELIMITACAO":delimitacao,"PERFIL_PLANEJAMENTO":planejamento,"MOTOR_ESPECIALIZADO":motor,"STATUS":status}
def pode_delimitar(tipo):return capability(tipo)["PERFIL_DELIMITACAO"] is not None
def pode_planejar(tipo):return capability(tipo)["PERFIL_PLANEJAMENTO"] is not None
