import re
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = tuple(sorted((ROOT / ".github" / "workflows").glob("*.yml")))
IMMUTABLE_USE = re.compile(
    r"^\s*uses:\s+(?P<owner>[^/\s]+)/(?P<name>[^@\s]+)@(?P<sha>[0-9a-f]{40})(?:\s+#\s+\S+)?\s*$",
    re.MULTILINE,
)
APPROVED_ACTIONS = {
    ("actions", "checkout"): "11d5960a326750d5838078e36cf38b85af677262",
    ("actions", "setup-python"): "a26af69be951a213d495a4c3e4e4022e16d87065",
    ("astral-sh", "setup-uv"): "c771a70e6277c0a99b617c7a806ffedaca235ff9",
}


def _workflow_texts() -> dict[Path, str]:
    return {path: path.read_text(encoding="utf-8") for path in WORKFLOWS}


def test_third_party_actions_are_official_and_immutably_pinned():
    references = []
    for path, workflow in _workflow_texts().items():
        raw_uses = re.findall(r"^\s*uses:\s+(\S+)", workflow, re.MULTILINE)
        matches = tuple(IMMUTABLE_USE.finditer(workflow))
        assert len(matches) == len(raw_uses), path
        references.extend(
            (match["owner"], match["name"], match["sha"])
            for match in matches
        )

    assert references
    for owner, name, sha in references:
        assert APPROVED_ACTIONS[(owner, name)] == sha


def test_every_checkout_disables_persisted_credentials():
    for path, workflow in _workflow_texts().items():
        starts = [match.start() for match in re.finditer(r"^\s*- (?:name:.*\n\s+)?uses:\s+actions/checkout@", workflow, re.MULTILINE)]
        for index, start in enumerate(starts):
            end = starts[index + 1] if index + 1 < len(starts) else len(workflow)
            assert re.search(r"^\s+persist-credentials:\s+false\s*$", workflow[start:end], re.MULTILINE), path


def test_dependency_workflows_use_locked_uv_and_exports_are_generated_only():
    workflows = _workflow_texts()
    uv_workflows = {path: text for path, text in workflows.items() if "uv sync" in text}
    assert {path.name for path in uv_workflows} == {
        "core-safety.yml", "lint.yml", "quality-depth.yml"
    }
    for path, workflow in uv_workflows.items():
        assert "uv sync --locked --no-install-project" in workflow, path
        assert "uv run --no-sync" in workflow, path
        assert "pip install" not in workflow, path
    for name in ("requirements.txt", "requirements-dev.txt"):
        export = (ROOT / name).read_text(encoding="utf-8")
        assert export.startswith("# This file was autogenerated by uv")
        assert "--hash=sha256:" in export


def test_project_and_lock_are_consistent_and_python_is_bounded():
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    assert project["project"]["requires-python"] == ">=3.13,<3.15"
    assert project["tool"]["uv"]["package"] is False
    assert lock["requires-python"] == ">=3.13, <3.15"
    assert lock["revision"] >= 1


def _locked_packages(lock: dict) -> dict[str, dict]:
    return {package["name"]: package for package in lock["package"]}


def _dependency_closure(packages: dict[str, dict], roots: set[str]) -> set[str]:
    found = set()
    visited = set()
    pending = [{"name": name} for name in roots]
    while pending:
        dependency = pending.pop()
        name = dependency["name"]
        extras = tuple(sorted(dependency.get("extra", [])))
        if (name, extras) in visited:
            continue
        visited.add((name, extras))
        found.add(name)
        package = packages[name]
        pending.extend(package.get("dependencies", []))
        for extra in extras:
            pending.extend(package.get("optional-dependencies", {}).get(extra, []))
    return found


def _export_entries(name: str) -> dict[str, tuple[str, set[str]]]:
    text = (ROOT / name).read_text(encoding="utf-8")
    starts = list(re.finditer(r"(?m)^([a-zA-Z0-9_.-]+)==([^ ;\\]+).*$", text))
    entries = {}
    for index, match in enumerate(starts):
        end = starts[index + 1].start() if index + 1 < len(starts) else len(text)
        hashes = set(re.findall(r"--hash=sha256:([0-9a-f]{64})", text[match.start():end]))
        entries[match.group(1)] = (match.group(2), hashes)
    return entries


def test_compatibility_exports_exactly_match_lock_graph_and_hashes():
    lock = tomllib.loads((ROOT / "uv.lock").read_text(encoding="utf-8"))
    packages = _locked_packages(lock)
    project = packages["padrao-laudos-periciais"]
    runtime_roots = {row["name"] for row in project["dependencies"]}
    dev_roots = runtime_roots | {
        row["name"] for row in project["dev-dependencies"]["dev"]
    }
    expected_names = {
        "requirements.txt": _dependency_closure(packages, runtime_roots),
        "requirements-dev.txt": _dependency_closure(packages, dev_roots),
    }

    for export_name, names in expected_names.items():
        entries = _export_entries(export_name)
        assert set(entries) == names
        for name, (version, hashes) in entries.items():
            package = packages[name]
            locked_hashes = {
                artifact["hash"].removeprefix("sha256:")
                for artifact in ([package.get("sdist")] if package.get("sdist") else [])
                + package.get("wheels", [])
            }
            assert version == package["version"]
            assert hashes == locked_hashes


def test_e1a_surface_has_no_floating_action_refs():
    surface = "\n".join(_workflow_texts().values()).casefold()
    for value in ("@latest", "@main", "@master", "@head"):
        assert value not in surface
    assert not re.search(r"uses:\s+[^\s]+@v\d+(?:\s|$)", surface)
